import type {
  PortfolioItem,
  PricePoint,
  WatchlistItem,
} from "@/lib/types/investment";

export const samplePrices: PricePoint[] = Array.from(
  { length: 90 },
  (_, index) => {
    const base = 1000 + index * 4;
    const cycle = Math.sin(index / 5) * 24;
    const pullback = index > 55 && index < 68 ? -70 : 0;
    const close = Math.max(850, Math.round(base + cycle + pullback));
    return {
      date: new Date(Date.UTC(2025, 9, index + 1)).toISOString().slice(0, 10),
      open: close - 5,
      high: close + 12,
      low: close - 14,
      close,
      volume: 1_000_000 + index * 2500,
    };
  },
);

export const samplePortfolio: PortfolioItem[] = [
  {
    id: "p1",
    name: "Bank Central Asia",
    type: "stock",
    ticker: "BBCA.JK",
    buyPrice: 9000,
    quantity: 120,
    currentPrice: 9700,
    buyDate: "2025-06-10",
    notes:
      "Bank Central Asia Tbk. — Perbankan [Ticker teruji di Google Finance]",
    riskCategory: "high",
    dataSource: "mock_data",
  },
  {
    id: "p2",
    name: "Bank Rakyat Indonesia",
    type: "stock",
    ticker: "",
    buyPrice: 5200,
    quantity: 300,
    currentPrice: 5050,
    buyDate: "2025-09-01",
    notes:
      "Bank Rakyat Indonesia Tbk. — Perbankan [Ticker BBRI.JK - coba format BBRI:IDX]",
    riskCategory: "high",
    dataSource: "mock_data",
  },
  {
    id: "p3",
    name: "Telkom Indonesia",
    type: "stock",
    ticker: "",
    buyPrice: 3200,
    quantity: 200,
    currentPrice: 3150,
    buyDate: "2025-12-15",
    notes:
      "Telkom Indonesia Tbk. — Telekomunikasi [Ticker TLKM.JK - coba format TLKM:IDX]",
    riskCategory: "medium",
    dataSource: "mock_data",
  },
  {
    id: "p4",
    name: "Astra International",
    type: "stock",
    ticker: "",
    buyPrice: 6500,
    quantity: 150,
    currentPrice: 6400,
    buyDate: "2026-01-10",
    notes:
      "Astra International Tbk. — Otomotif / Holding [Ticker ASII.JK - coba format ASII:IDX]",
    riskCategory: "medium",
    dataSource: "mock_data",
  },
  {
    id: "p5",
    name: "GoTo",
    type: "stock",
    ticker: "",
    buyPrice: 250,
    quantity: 10000,
    currentPrice: 245,
    buyDate: "2026-02-20",
    notes:
      "GoTo Gojek Tokopedia Tbk. — Teknologi [Ticker GOTO.JK - coba format GOTO:IDX]",
    riskCategory: "high",
    dataSource: "mock_data",
  },
  {
    id: "p6",
    name: "Unilever Indonesia",
    type: "stock",
    ticker: "",
    buyPrice: 7850,
    quantity: 60,
    currentPrice: 7780,
    buyDate: "2026-03-05",
    notes:
      "Unilever Indonesia Tbk. — Konsumsi [Ticker UNVR.JK - coba format UNVR:IDX]",
    riskCategory: "medium",
    dataSource: "mock_data",
  },
  {
    id: "p7",
    name: "Adaro Energy Indonesia",
    type: "stock",
    ticker: "",
    buyPrice: 2000,
    quantity: 400,
    currentPrice: 1980,
    buyDate: "2026-04-18",
    notes:
      "Adaro Energy Indonesia Tbk. — Energi / Tambang [Ticker ADRO.JK - coba format ADRO:IDX]",
    riskCategory: "high",
    dataSource: "mock_data",
  },
  {
    id: "p8",
    name: "Sucorinvest Money Market Fund",
    type: "money_market_fund",
    buyPrice: 1000,
    quantity: 5000,
    currentPrice: 1015,
    buyDate: "2026-01-02",
    notes: "RDPU populer — Sucorinvest Money Market Fund (SMMF)",
    riskCategory: "low",
    dataSource: "mock_data",
  },
  {
    id: "p9",
    name: "Batavia Dana Kas Maxima",
    type: "money_market_fund",
    buyPrice: 1000,
    quantity: 4800,
    currentPrice: 1014,
    buyDate: "2026-02-10",
    notes: "RDPU populer — Batavia Dana Kas Maxima (BDKM)",
    riskCategory: "low",
    dataSource: "mock_data",
  },
  {
    id: "p10",
    name: "Mandiri Investa Pasar Uang",
    type: "money_market_fund",
    buyPrice: 1000,
    quantity: 4700,
    currentPrice: 1013,
    buyDate: "2026-02-20",
    notes: "RDPU populer — Mandiri Investa Pasar Uang (MIPU)",
    riskCategory: "low",
    dataSource: "mock_data",
  },
  {
    id: "p14",
    name: "Bahana Dana Likuid",
    type: "money_market_fund",
    buyPrice: 1000,
    quantity: 4500,
    currentPrice: 1012,
    buyDate: "2026-03-01",
    notes: "RDPU populer — Bahana Dana Likuid (BDL)",
    riskCategory: "low",
    dataSource: "mock_data",
  },
  {
    id: "p15",
    name: "Danareksa Seruni Pasar Uang",
    type: "money_market_fund",
    buyPrice: 1000,
    quantity: 5200,
    currentPrice: 1016,
    buyDate: "2026-03-15",
    notes: "RDPU populer — Danareksa Seruni Pasar Uang",
    riskCategory: "low",
    dataSource: "mock_data",
  },
  {
    id: "p16",
    name: "Sucorinvest Equity Fund",
    type: "equity_fund",
    buyPrice: 2200,
    quantity: 1200,
    currentPrice: 2350,
    buyDate: "2026-01-15",
    notes: "RDS populer — Sucorinvest Equity Fund (SEF)",
    riskCategory: "high",
    dataSource: "mock_data",
  },
  {
    id: "p11",
    name: "Schroder Dana Prestasi Plus",
    type: "equity_fund",
    buyPrice: 2800,
    quantity: 900,
    currentPrice: 2925,
    buyDate: "2026-02-08",
    notes: "RDS populer — Schroder Dana Prestasi Plus",
    riskCategory: "high",
    dataSource: "mock_data",
  },
  {
    id: "p12",
    name: "BNP Paribas Pesona",
    type: "equity_fund",
    buyPrice: 2400,
    quantity: 850,
    currentPrice: 2520,
    buyDate: "2026-03-01",
    notes: "RDS populer — BNP Paribas Pesona",
    riskCategory: "high",
    dataSource: "mock_data",
  },
  {
    id: "p13",
    name: "Manulife Saham Andalan",
    type: "equity_fund",
    buyPrice: 2100,
    quantity: 1100,
    currentPrice: 2250,
    buyDate: "2026-03-20",
    notes: "RDS populer — Manulife Saham Andalan (MSA)",
    riskCategory: "high",
    dataSource: "mock_data",
  },
  {
    id: "p17",
    name: "Ashmore Dana Ekuitas Nusantara",
    type: "equity_fund",
    buyPrice: 1800,
    quantity: 1400,
    currentPrice: 1920,
    buyDate: "2026-04-10",
    notes: "RDS populer — Ashmore Dana Ekuitas Nusantara",
    riskCategory: "high",
    dataSource: "mock_data",
  },
];

export const sampleWatchlist: WatchlistItem[] = [
  {
    id: "w1",
    name: "BBCA.JK",
    type: "stock",
    targetBuyZone: "9.500 - 10.000",
    notes: "Bank Central Asia Tbk. — Perbankan [Google Finance: ✓ Aktif]",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w2",
    name: "^JKSE",
    type: "stock",
    targetBuyZone: "7.200 - 7.400",
    notes: "Indeks Harga Saham Gabungan IHSG [Google Finance: ✓ Aktif]",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w3",
    name: "Bank Rakyat Indonesia",
    type: "stock",
    targetBuyZone: "4.500 - 4.750",
    notes:
      "Bank Rakyat Indonesia Tbk. — Perbankan [Google Finance: Gunakan BBRI:IDX]",
    status: "waiting",
    dataSource: "mock_data",
  },
  {
    id: "w4",
    name: "Sucorinvest Money Market Fund",
    type: "money_market_fund",
    targetBuyZone: "NAV stabil > 1.01",
    notes: "Reksa Dana Pasar Uang populer",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w5",
    name: "Batavia Dana Kas Maxima",
    type: "money_market_fund",
    targetBuyZone: "NAV stabil > 1.01",
    notes: "Reksa Dana Pasar Uang populer",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w10",
    name: "Mandiri Investa Pasar Uang",
    type: "money_market_fund",
    targetBuyZone: "NAV stabil > 1.01",
    notes: "Reksa Dana Pasar Uang populer",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w11",
    name: "Bahana Dana Likuid",
    type: "money_market_fund",
    targetBuyZone: "NAV stabil > 1.01",
    notes: "Reksa Dana Pasar Uang populer",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w12",
    name: "Danareksa Seruni Pasar Uang",
    type: "money_market_fund",
    targetBuyZone: "NAV stabil > 1.01",
    notes: "Reksa Dana Pasar Uang populer",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w13",
    name: "Sucorinvest Equity Fund",
    type: "equity_fund",
    targetBuyZone: "2200 - 2400",
    notes: "Reksa Dana Saham populer",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w6",
    name: "Schroder Dana Prestasi Plus",
    type: "equity_fund",
    targetBuyZone: "2800 - 2950",
    notes: "RDS populer — Schroder Dana Prestasi Plus",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w7",
    name: "BNP Paribas Pesona",
    type: "equity_fund",
    targetBuyZone: "2400 - 2550",
    notes: "RDS populer — BNP Paribas Pesona",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w8",
    name: "Manulife Saham Andalan",
    type: "equity_fund",
    targetBuyZone: "2100 - 2300",
    notes: "RDS populer — Manulife Saham Andalan (MSA)",
    status: "watching",
    dataSource: "mock_data",
  },
  {
    id: "w9",
    name: "Ashmore Dana Ekuitas Nusantara",
    type: "equity_fund",
    targetBuyZone: "1800 - 1950",
    notes: "RDS populer — Ashmore Dana Ekuitas Nusantara",
    status: "watching",
    dataSource: "mock_data",
  },
];
